# Generated by Django 4.2.6 on 2024-01-01 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingdetails',
            name='dropOff',
            field=models.CharField(default='Unspecified', max_length=200),
            preserve_default=False,
        ),
    ]
